# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DrawChart' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DrawChart

  pod 'SnapKit'
  pod 'Then'
  pod 'RxSwift'
  pod 'RxCocoa'

end
